/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditOrderDialog.java
 *
 * Created on 02.03.2009, 15:43:08
 */

package jbookmanager.view;

import java.util.ResourceBundle;
import javax.swing.DefaultListModel;
import jbookmanager.controller.LibraryManager;

/**
 *
 * @author uli
 */
public class EditOrderDialog extends javax.swing.JDialog {

    /**
     * Creates new form EditOrderDialog
     * @param parent
     * @param modal 
     */
    public EditOrderDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Init the book title list
        updateBookTitleList();
    }

    public void updateBookTitleList()
    {
        ((DefaultListModel)bookTitleList.getModel()).removeAllElements();
        for(String s : LibraryManager.library.getTitles())
        {
            ((DefaultListModel)bookTitleList.getModel()).addElement(s);
        }        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        bookTitleScrollPane = new javax.swing.JScrollPane();
        bookTitleList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle( i18n.getString("EditOrderDialog.title")); // NOI18N

        nameLabel.setText( i18n.getString("EditOrderDialog.nameLabel.text")); // NOI18N

        bookTitleList.setModel(new DefaultListModel());
        bookTitleScrollPane.setViewportView(bookTitleList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookTitleScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookTitleScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ResourceBundle i18n = ResourceBundle.getBundle("jbookmanager/view/Bundle");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList bookTitleList;
    private javax.swing.JScrollPane bookTitleScrollPane;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables

}
