/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JBookManagerFrame.java
 *
 * Created on 26.02.2009, 19:37:49
 */
package jbookmanager.view;

import java.io.File;
import java.io.IOException;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileFilter;
import jbookmanager.model.JBookManagerConfiguration;
import jbookmanager.model.Library;
import jbookmanager.controller.LibraryManager;

/**
 *
 * @author uli
 */
public class JBookManagerFrame extends javax.swing.JFrame
{

    /** Creates new form JBookManagerFrame */
    public JBookManagerFrame()
    {
        initComponents();
        
        fc.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f)
            {
                try
                {
                    if(f.isDirectory()) {return true;}
                    return f.getCanonicalPath().endsWith(".lgz");
                }
                catch (IOException ex)
                {
                    Logger.getLogger(JBookManagerFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                return false; //File is not accessible so don't accept it
            }

            @Override
            public String getDescription()
            {
                return "Library data files";
            }
        });
        
        initLibrary();
        initBookList();
        updateList();
    }

    private void initBookList()
    {
        bookList.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e)
            {
                int index = e.getFirstIndex();
                titleField.setText(library.getBookAt(index).getTitle());
                isbnFormattedField.setText(library.getBookAt(index).getIsbn());
                priceField.setText(Double.toString(library.getBookAt(index).getPrice()));
                countSpinner.setValue(library.getBookAt(index).getCount());
                commentField.setText(library.getBookAt(index).getComment());
            }
        });
    }

    private void updateList()
    {
        library.updateTitleListModel((DefaultListModel)bookList.getModel());
    }

    private void initLibrary()
    {
        try
        {
            String libraryFilename = config.getProperty("LibraryFile");
            if (!libraryFilename.isEmpty())
            {
                library = LibraryManager.readLibrary(libraryFilename);
            }
            else //Create a new library
            {
                fc.setDialogTitle(i18n.getString("Create new library"));
                fc.showSaveDialog(this);
                File libraryFile = fc.getSelectedFile();
                if(!(libraryFile == null))
                {config.setProperty("LibraryFile", libraryFile.getAbsolutePath());}
                library = new Library();
            }
        }
        catch (IOException ex)
        {
            Logger.getLogger(JBookManagerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newBookButton = new javax.swing.JButton();
        filterLabel = new javax.swing.JLabel();
        filterColumnComboBox = new javax.swing.JComboBox();
        filterTypeComboBox = new javax.swing.JComboBox();
        filterStringField = new javax.swing.JTextField();
        filterOkButton = new javax.swing.JButton();
        filterDeleteButton = new javax.swing.JButton();
        bookScrollPane = new javax.swing.JScrollPane();
        bookList = new javax.swing.JList();
        titleLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        countLabel = new javax.swing.JLabel();
        commentLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        isbnFormattedField = new javax.swing.JFormattedTextField();
        priceField = new javax.swing.JFormattedTextField();
        countSpinner = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        commentField = new javax.swing.JEditorPane();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newLibraryMenuItem = new javax.swing.JMenuItem();
        saveLibraryMenuItem = new javax.swing.JMenuItem();
        saveCopyMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle( i18n.getString("JBookManagerFrame.title")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        newBookButton.setText( i18n.getString("JBookManagerFrame.newBookButton.text")); // NOI18N
        newBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookButtonActionPerformed(evt);
            }
        });

        filterLabel.setText( i18n.getString("JBookManagerFrame.filterLabel.text")); // NOI18N

        filterColumnComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISBN", "Title", "Authors", "Price", "Count", "Comment" }));

        filterTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Contains", "Is", "Regex" }));

        filterOkButton.setText( i18n.getString("JBookManagerFrame.filterOkButton.text")); // NOI18N

        filterDeleteButton.setText( i18n.getString("JBookManagerFrame.filterDeleteButton.text")); // NOI18N

        bookList.setModel(new DefaultListModel());
        bookScrollPane.setViewportView(bookList);

        titleLabel.setText( i18n.getString("JBookManagerFrame.titleLabel.text")); // NOI18N

        isbnLabel.setText( i18n.getString("JBookManagerFrame.isbnLabel.text")); // NOI18N

        priceLabel.setText( i18n.getString("JBookManagerFrame.priceLabel.text")); // NOI18N

        countLabel.setText( i18n.getString("JBookManagerFrame.countLabel.text")); // NOI18N

        commentLabel.setText( i18n.getString("JBookManagerFrame.commentLabel.text")); // NOI18N

        titleField.setText( i18n.getString("JBookManagerFrame.titleField.text")); // NOI18N

        try {
            isbnFormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        priceField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));

        countSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jScrollPane2.setViewportView(commentField);

        updateButton.setText( i18n.getString("JBookManagerFrame.updateButton.text")); // NOI18N

        deleteButton.setText( i18n.getString("JBookManagerFrame.deleteButton.text")); // NOI18N

        fileMenu.setText( i18n.getString("JBookManagerFrame.fileMenu.text")); // NOI18N

        newLibraryMenuItem.setText( i18n.getString("JBookManagerFrame.newLibraryMenuItem.text")); // NOI18N
        newLibraryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLibraryMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newLibraryMenuItem);

        saveLibraryMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveLibraryMenuItem.setText( i18n.getString("JBookManagerFrame.saveLibraryMenuItem.text")); // NOI18N
        saveLibraryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveLibraryMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveLibraryMenuItem);

        saveCopyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        saveCopyMenuItem.setText( i18n.getString("JBookManagerFrame.saveCopyMenuItem.text")); // NOI18N
        saveCopyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCopyMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveCopyMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText( i18n.getString("JBookManagerFrame.editMenu.text")); // NOI18N
        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(filterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterColumnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bookScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filterTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterStringField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterDeleteButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addComponent(isbnLabel)
                            .addComponent(countLabel)
                            .addComponent(priceLabel))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(countSpinner)
                            .addComponent(priceField)
                            .addComponent(isbnFormattedField)
                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(commentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterColumnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterStringField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterOkButton)
                    .addComponent(filterLabel)
                    .addComponent(newBookButton)
                    .addComponent(filterDeleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleLabel)
                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isbnLabel)
                            .addComponent(isbnFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLabel)
                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countLabel)
                            .addComponent(countSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(commentLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateButton)
                            .addComponent(deleteButton)))
                    .addComponent(bookScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveCopyMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveCopyMenuItemActionPerformed
    {//GEN-HEADEREND:event_saveCopyMenuItemActionPerformed
        fc.setDialogTitle(i18n.getString("Save copy"));
        fc.showSaveDialog(this);
        String filename = fc.getSelectedFile().getAbsolutePath();
        LibraryManager.writeLibrary(library, filename);
    }//GEN-LAST:event_saveCopyMenuItemActionPerformed

    private void saveLibraryMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveLibraryMenuItemActionPerformed
    {//GEN-HEADEREND:event_saveLibraryMenuItemActionPerformed
        LibraryManager.writeLibrary(library, config.getProperty("LibraryFile"));
    }//GEN-LAST:event_saveLibraryMenuItemActionPerformed

    private void newLibraryMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newLibraryMenuItemActionPerformed
    {//GEN-HEADEREND:event_newLibraryMenuItemActionPerformed
        int sel = JOptionPane.showConfirmDialog(this,
                                                i18n.getString("Save the current library?"),
                                                "Save current library",
                                                JOptionPane.YES_NO_OPTION,
                                                JOptionPane.QUESTION_MESSAGE);
        //Save the library if the user clicked "Yes"
        if(sel == JOptionPane.YES_OPTION)
        {
            LibraryManager.writeLibrary(library, config.getProperty("LibraryFile"));
        }
        library = new Library();
    }//GEN-LAST:event_newLibraryMenuItemActionPerformed

    private void newBookButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newBookButtonActionPerformed
    {//GEN-HEADEREND:event_newBookButtonActionPerformed
        NewBookDialog newBookDialog = new NewBookDialog(this, true);
        newBookDialog.setLibrary(library);
        newBookDialog.setVisible(true);
        updateList();
    }//GEN-LAST:event_newBookButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        try
        {
            config.save();
        }
        catch (IOException ex)
        {
            Logger.getLogger(JBookManagerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new JBookManagerFrame().setVisible(true);
            }
        });
    }
    public static Library library = new Library();
    private JFileChooser fc = new JFileChooser();
    private JBookManagerConfiguration config = new JBookManagerConfiguration();
    private ResourceBundle i18n = ResourceBundle.getBundle("jbookmanager/view/Bundle");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList bookList;
    private javax.swing.JScrollPane bookScrollPane;
    private javax.swing.JEditorPane commentField;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JLabel countLabel;
    private javax.swing.JSpinner countSpinner;
    private javax.swing.JButton deleteButton;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JComboBox filterColumnComboBox;
    private javax.swing.JButton filterDeleteButton;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JButton filterOkButton;
    private javax.swing.JTextField filterStringField;
    private javax.swing.JComboBox filterTypeComboBox;
    private javax.swing.JFormattedTextField isbnFormattedField;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton newBookButton;
    private javax.swing.JMenuItem newLibraryMenuItem;
    private javax.swing.JFormattedTextField priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JMenuItem saveCopyMenuItem;
    private javax.swing.JMenuItem saveLibraryMenuItem;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
