/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListEditComboBox.java
 *
 * Created on 27.02.2009, 14:41:35
 */

package jbookmanager.view;

import java.util.List;
import java.util.Vector;
import javax.swing.JComboBox;

/**
 *
 * @author uli
 */
public class ListEditComboBox extends JComboBox {

    /** Creates new form BeanForm
     * @param data The combo box data
     */
    public ListEditComboBox(List<Object> data) {
        initComponents();
        setData(data);
    }

    public void setData(List<Object> data)
    {
        for(Object s : data)
        {
            addItem(s);
        }
    }

    public Vector<String> getData()
    {
        Vector<String> ret = new Vector<String>();

        for (int i = 0; i < getItemCount(); i++)
        {
            ret.add((String) getItemAt(i));
        }
        return ret;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setEditable(true);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
