/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewBookDialog.java
 *
 * Created on 26.02.2009, 20:11:39
 */
package jbookmanager.view;

import java.io.IOException;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jbookmanager.model.AmazonBookInfo;
import jbookmanager.model.Book;

/**
 *
 * @author uli
 */
public class NewBookDialog extends javax.swing.JDialog
{

    /**
     * Creates new form NewBookDialog
     * @param parent
     * @param modal
     */
    public NewBookDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isbnLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        commentLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        countLabel = new javax.swing.JLabel();
        countSpinner = new jbookmanager.view.NumberSpinner();
        commentScrollPane = new javax.swing.JScrollPane();
        commentField = new javax.swing.JTextPane();
        priceField = new javax.swing.JTextField();
        amazonButton = new javax.swing.JButton();
        isbnField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle( i18n.getString("NewBookDialog.title")); // NOI18N

        isbnLabel.setText( i18n.getString("NewBookDialog.isbnLabel.text")); // NOI18N

        titleLabel.setText( i18n.getString("NewBookDialog.titleLabel.text")); // NOI18N

        titleField.setText( i18n.getString("NewBookDialog.titleField.text")); // NOI18N

        priceLabel.setText( i18n.getString("NewBookDialog.priceLabel.text")); // NOI18N

        commentLabel.setText( i18n.getString("NewBookDialog.commentLabel.text")); // NOI18N

        okButton.setText( i18n.getString("NewBookDialog.okButton.text")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        countLabel.setText( i18n.getString("NewBookDialog.countLabel.text")); // NOI18N

        countSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));

        commentScrollPane.setViewportView(commentField);

        priceField.setText( i18n.getString("NewBookDialog.priceField.text")); // NOI18N

        amazonButton.setText( i18n.getString("NewBookDialog.amazonButton.text")); // NOI18N
        amazonButton.setToolTipText( i18n.getString("NewBookDialog.amazonButton.toolTipText")); // NOI18N
        amazonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amazonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(commentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(commentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(countLabel)
                            .addComponent(titleLabel)
                            .addComponent(isbnLabel)
                            .addComponent(priceLabel))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(countSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(titleField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(isbnField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amazonButton, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                            .addComponent(priceField, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLabel)
                    .addComponent(amazonButton)
                    .addComponent(isbnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(commentLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commentScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
    {//GEN-HEADEREND:event_okButtonActionPerformed
        Book b = new Book();
        //ISBN
        b.setIsbn(isbnField.getText());
        //Title
        String title = titleField.getText();
        if (title.isEmpty())
        {
            JOptionPane.showMessageDialog(this,  i18n.getString("EmptyTitleErrorMessage"),  i18n.getString("EmptyTitleErrorTitle"),
                                          JOptionPane.ERROR_MESSAGE);
            return;
        }
        b.setTitle(title);
        //Price
        b.setPrice(new Double(priceField.getText().replace(',', '.')));
        //Count
        b.setCount(countSpinner.getIntValue());
        //Comment
        b.setComment(commentField.getText());

        /**
         * Add the book to the library
         */
        JBookManagerFrame.library.addBook(b);

        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void amazonButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_amazonButtonActionPerformed
    {//GEN-HEADEREND:event_amazonButtonActionPerformed
        try
        {
            Book amazonBook = AmazonBookInfo.getBookInfo(isbnField.getText());
            titleField.setText(amazonBook.getTitle());
            priceField.setText(Double.toString(amazonBook.getPrice()));
            commentField.setText(amazonBook.getComment());

        }
        catch (IOException ex)
        {
            JOptionPane.showMessageDialog(this, i18n.getString("IOErrorMessage"), i18n.getString("IOErrorTitle"),
                                          JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(NewBookDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        /**
         * Occurs if no match has been found
         * -> the downloaded page doesn't describe a book
         */
        catch (IllegalStateException ex)
        {
            JOptionPane.showMessageDialog(this, i18n.getString("NoSuchBookErrorMessage"), i18n.getString(
                    "NoSuchBookErrorTitle"), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(NewBookDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_amazonButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                NewBookDialog dialog = new NewBookDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private ResourceBundle i18n = ResourceBundle.getBundle("jbookmanager/view/Bundle");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton amazonButton;
    private javax.swing.JTextPane commentField;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JScrollPane commentScrollPane;
    private javax.swing.JLabel countLabel;
    private jbookmanager.view.NumberSpinner countSpinner;
    private javax.swing.JTextField isbnField;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
